[package]
name = "lumen"
version = "2.5.0"
edition = "2024"
license = "MIT"
description = "lumen is a command-line tool that uses AI to generate commit messages and summarise git diffs or past commits."
keywords = ["cli", "terminal", "ai", "git", "commit"]
categories = ["command-line-interface", "command-line-utilities"]
repository = "https://github.com/jnsahaj/lumen"

[dependencies]
clap = { version = "4.4", features = ["derive", "env"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
genai = "0.4"
spinoff = { version = "0.8.0", features = ["dots"] }
thiserror = "1.0"
indoc = "2.0.5"
xml-rs = "0.8"
dirs = "6.0.0"
inquire = "0.7"
env_logger = "0.11.8"
log = "0.4.29"

[profile.release]
lto = true
